### ISSUE TITLE
Make deploy to heroku button

### ISSUE THREAD

**Issue by branchmaster** [poseidon-code/youtube-viewbot#3]
Hi Paritam ,
please make deploy to heroku button for easy deploy & make this project permanent usage free of personal system usage or any paid invoice server must be bill , all the buildpacks like selenium , chrome headless or ... are exist.
waiting for your response
finest regards

**Comment by poseidon-code** [comment]
Reasons why this have not yet been implemented :
1. This requires a completely working system on the cloud, which cost money.
2. Personally making and testing this new implementation will get expensive.
3. Freely self hosting does not guarantees 100% uptime.
4. **I myself** can not freely host this service due to above limitations.

**Although**
The code base can be changed to a request based server that runs on a cloud hosted system, where users can put their preferred youtube video and watch time and the cloud server can keep watching the video to increase views. 
The problem is, I cannot have any access to such cloud server where I can test this feature and I do not have money to freely host it on the cloud.
Although one thing that I can do is to change the code base to a web server based design, and make a simple deployment script to deploy this `youtube-viewbot` to any server over the internet, so as to anyone can host their own free viewbot service.

That said, I currently have no plans on working on this feature but I welcome any contributor to implement this feature.
